/**
 * Builds the dashboard page into shippable artefacts.
 *
 * `web/dashboard.html` is the editable source — real HTML, real CSS, real JS,
 * openable in an editor with syntax highlighting. It cannot be imported
 * directly by the Worker, which has no filesystem, so this script turns it
 * into a TypeScript module holding the markup as a string.
 *
 * Two outputs:
 *
 *   src/dashboard/page.ts        served by the bot at GET /dashboard
 *   web/dashboard.standalone.html  opens from disk with the sample data, so
 *                                  the page can be worked on with no backend
 *
 * Run: npm run build:page
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(resolve(root, p), 'utf8');

const html = read('web/dashboard.html');
const sample = read('docs/dashboard-sample.json');

/* The font CSS lives in its own module because it is 145KB of base64 and
   would make every diff of this script unreadable. */
const fontsModule = read('src/dashboard/fonts.ts');
const fontCss = fontsModule.slice(
  fontsModule.indexOf('String.raw`') + 'String.raw`'.length,
  fontsModule.lastIndexOf('`;'),
);

/* ------------------------------------------------------------------ *
 * Server artefact
 * ------------------------------------------------------------------ */

const forServer = html
  .replace('/*__FONTS__*/', fontCss.trim())
  // The server always supplies real config, so the sample would be dead
  // weight in every response.
  .replace('<!--__SAMPLE__-->', '');

/**
 * Escapes text for embedding in a TypeScript template literal.
 *
 * Order is load-bearing: backslashes first, or the escapes added for the
 * backtick and `${` would themselves be escaped a second time.
 */
function forTemplateLiteral(text) {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

const pageTs = `/**
 * The dashboard page, as served.
 *
 * GENERATED by scripts/build-page.mjs from web/dashboard.html — do not edit
 * this file. Edit the HTML and run \\\`npm run build:page\\\`.
 *
 * The page is a shell: it carries no data, and fetches /dashboard/api on load.
 * Config is substituted below rather than fetched, because the reader already
 * had to present the token to receive this page at all — asking for it a
 * second time would add a login screen protecting nothing.
 */

export interface ShellOptions {
  /** Passed to the API call the page makes. */
  token: string;
  /** Path of the JSON endpoint, e.g. /dashboard/api */
  apiBase: string;
  days: number;
  /** '' for the configured number, 'all' for every number. */
  phone: string;
}

const TEMPLATE = \`${forTemplateLiteral(forServer)}\`;

/**
 * Escapes a value for a single-quoted JavaScript string literal.
 *
 * The token is operator-supplied rather than attacker-supplied, but it is
 * still untrusted input reaching a script context — a stray quote would break
 * the page, and a crafted one would inject.
 */
function jsString(value: string): string {
  return String(value)
    .replace(/\\\\/g, '\\\\\\\\')
    .replace(/'/g, "\\\\'")
    .replace(/</g, '\\\\x3c')
    .replace(/[\\r\\n]/g, '');
}

export function renderShell(opts: ShellOptions): string {
  return TEMPLATE.replace('__TOKEN__', jsString(opts.token))
    .replace('__API_BASE__', jsString(opts.apiBase))
    .replace('__DAYS__', jsString(String(opts.days)))
    .replace('__PHONE__', jsString(opts.phone));
}
`;

mkdirSync(resolve(root, 'src/dashboard'), { recursive: true });
writeFileSync(resolve(root, 'src/dashboard/page.ts'), pageTs, 'utf8');

/* ------------------------------------------------------------------ *
 * Standalone artefact
 * ------------------------------------------------------------------ */

const standalone = html
  .replace('/*__FONTS__*/', fontCss.trim())
  .replace(
    '<!--__SAMPLE__-->',
    `<script>/* Bundled so this file works with no server. The live page never\n   reaches this: CFG.token is substituted, so LIVE is true. */\nconst SAMPLE = ${sample.trim()};</script>`,
  );

writeFileSync(resolve(root, 'web/dashboard.standalone.html'), standalone, 'utf8');

console.log('build:page');
console.log('  src/dashboard/page.ts          ', (pageTs.length / 1024).toFixed(0) + 'KB');
console.log('  web/dashboard.standalone.html  ', (standalone.length / 1024).toFixed(0) + 'KB');
